### ISSUE TITLE
[FEAT] 스터디룸 예약에 SL 예약 지원

### ISSUE THREAD

**Issue by therealjamesjung** [se-gam/segam-backend#25]
개발단계에서는 없었던 SL 예약이 새로 추가됐습니다. SL 예약도 지원하기 위해서 크롤링 대상을 추가합니다.

![Screenshot 2024-04-15 at 12 23 33 PM](https://github.com/se-gam/segam-backend/assets/39877377/900ab79a-c770-41dd-b3bd-a65c44832bfc)

**Comment by luciancah** [comment]
이제 누가 라운지 자리 맡아주냐...
